# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asdgCMatrix_ <- function(XX_) {
    .Call(`_mtSCRABBLE_asdgCMatrix_`, XX_)
}

mSparse <- function(As, bs) {
    .Call(`_mtSCRABBLE_mSparse`, As, bs)
}

mMatrix <- function(As, bs) {
    .Call(`_mtSCRABBLE_mMatrix`, As, bs)
}

mSparseT <- function(As, bs) {
    .Call(`_mtSCRABBLE_mSparseT`, As, bs)
}

mMatrixT <- function(As, bs) {
    .Call(`_mtSCRABBLE_mMatrixT`, As, bs)
}

getZ <- function(As, bs) {
    .Call(`_mtSCRABBLE_getZ`, As, bs)
}

getA <- function(As, betas, gammas, ns) {
    .Call(`_mtSCRABBLE_getA`, As, betas, gammas, ns)
}

getB <- function(Ds, Zs, Ys, betas) {
    .Call(`_mtSCRABBLE_getB`, Ds, Zs, Ys, betas)
}

ToDense <- function(newXs) {
    .Call(`_mtSCRABBLE_ToDense`, newXs)
}

ToSparse <- function(newXs) {
    .Call(`_mtSCRABBLE_ToSparse`, newXs)
}

cDescent <- function(gamma_Y_B_Lambdas, As, zoness, newXs, nIters, nSDCIters, error_thresholds, iOuters) {
    .Call(`_mtSCRABBLE_cDescent`, gamma_Y_B_Lambdas, As, zoness, newXs, nIters, nSDCIters, error_thresholds, iOuters)
}

getS <- function(newXs, Lambdas, gammas) {
    .Call(`_mtSCRABBLE_getS`, newXs, Lambdas, gammas)
}

getY <- function(ss, Us, Vs) {
    .Call(`_mtSCRABBLE_getY`, ss, Us, Vs)
}

calculateError <- function(Xs, newXs, m1s, n1s) {
    .Call(`_mtSCRABBLE_calculateError`, Xs, newXs, m1s, n1s)
}

updateLambda <- function(Lambdas, newXs, newYs, gammas) {
    .Call(`_mtSCRABBLE_updateLambda`, Lambdas, newXs, newYs, gammas)
}

recoverData <- function(newXs) {
    .Call(`_mtSCRABBLE_recoverData`, newXs)
}

